{{- $serverUrl := .Values.serverUrl | required ".Values.serverUrl is required." -}}
{{- $clusterName := .Values.clusterName | required ".Values.clusterName is required." -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "so-virt.fullname" . }}
  labels: 
    {{- include "so-virt.labels" . | nindent 4 }}
spec:
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "so-virt.labels" . | nindent 8 }}
        {{- with .Values.pobLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: {{ include "so-virt.serviceAccountName" . }}
          containers:
          - name: {{ $.Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ $.Values.image.pullPolicy }}
            env:
            - name: SUSEOBSERVABILITY_API_URL
              value: {{$serverUrl}}
            - name: SUSEOBSERVABILITY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: API_KEY
                  name: {{ include "so-virt.fullname" . }}-secret
            - name: SUSEOBSERVABILITY_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: API_TOKEN
                  name: {{ include "so-virt.fullname" . }}-secret
            - name: KUBERNETES_IN_CLUSTER
              value: "true"
            - name: KUBERNETES_CLUSTER
              value: {{ $clusterName }}
            - name: INSTANCE_TYPE
              value: virt
            - name: INSTANCE_URL
              value: {{ $clusterName }}
            resources:
              {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: Never
          securityContext: 
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          terminationGracePeriodSeconds: 30
  schedule: "{{.Values.schedule}}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  concurrencyPolicy: Forbid
