apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "so-virt.fullname" . }}-role
  labels:
    {{- include "so-virt.labels" . | nindent 4 }}
rules:
- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachineinstances"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "so-virt.fullname" . }}-binding
  labels:
    {{- include "so-virt.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "so-virt.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "so-virt.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "so-virt.fullname" . }}-clusterrole
  labels:
    {{- include "so-virt.labels" . | nindent 4 }}
rules:
- apiGroups: ["kubevirt.io"]
  resources:
  - virtualmachineinstances
  verbs: ["list", "get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "so-virt.fullname" . }}-clusterrolebinding
  labels:
    {{- include "so-virt.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "so-virt.fullname" . }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "so-virt.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
