{{- $apiKey := .Values.apiKey | required ".Values.apiKey is required." -}}
{{- $apiToken := .Values.apiToken | required ".Values.apiToken is required." -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "so-virt.fullname" . }}-secret
  labels:
    {{- include "so-virt.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ $apiKey | b64enc }}
  API_TOKEN: {{ $apiToken | b64enc }}