apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "so-virt.serviceAccountName" . }}
  labels:
    {{- include "so-virt.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
