version: '3'

dotenv: ['./.env']

vars:
  IMAGE_REPO: "{{.USER}}/so-virt"
  VERSION: 0.0.1

tasks:
  run:
    silent: true
    cmds:
    - |
      if test -f ./conf.yaml; then
        export CONFIG_FILE=./conf.yaml
        go run ./cmd/sync/main.go
      else
        echo "Please create conf.yaml and set required values for your environment."
      fi

  docker-build:
    cmds:
      - docker build . -t {{.IMAGE_REPO}}:{{.VERSION}}
      - docker build . -t {{.IMAGE_REPO}}:latest
  docker-push:
    cmds:
      - echo $PASSWORD | docker login -u {{.USER}} --password-stdin
      - docker push {{.IMAGE_REPO}}:{{.VERSION}}
      - docker push {{.IMAGE_REPO}}:latest
